version: '3.9'

name: "imminent-bot"

networks:
 default:
  name: 'data'

volumes:
 data-pg:
 
services:
  postgres:
    container_name: 'data-pg'
    image: 'postgres:latest'
    ports:
      - '5432:5432'  
    environment: 
      POSTGRES_PASSWORD: 'postgrespw'
    volumes:
      - data-pg:/var/lib/postgresql/data

# docker compose up -d
# dotnet ef migrations add (name) -p Storage -s API                        (DO not copy)- migrations
# dotnet ef database update -p ImminentBot                            (DO not copy)- update db